using System.Text.Json;
namespace UTMMonitor;
public sealed class DocumentDetailsForm:Form
{
 public DocumentDetailsForm(DocumentRow d){Text=$"ТТН / справка — {d.Number} — {d.Direction}";Width=1200;Height=760;MinimumSize=new(900,600);StartPosition=FormStartPosition.CenterParent;Font=new("Segoe UI",9F);var tabs=new TabControl{Dock=DockStyle.Fill};var human=new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,Font=new("Segoe UI",10F)};human.Text=Human(d);var all=new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,Font=new("Consolas",9F)};all.Text=Fields(d.RawJson);var raw=new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,Font=new("Consolas",9F)};raw.Text=Pretty(d.RawJson);tabs.TabPages.Add(Page("Понятно человеку",human));tabs.TabPages.Add(Page("Все поля ЕГАИС",all));tabs.TabPages.Add(Page("Исходные данные",raw));Controls.Add(tabs);}
 static TabPage Page(string s,Control c){var p=new TabPage(s);p.Controls.Add(c);return p;}
 static string Human(DocumentRow d){var sb=new System.Text.StringBuilder();sb.AppendLine("════════════════════════════════════════════════════════════════");sb.AppendLine("ТТН / ДОКУМЕНТ ЕГАИС");sb.AppendLine("════════════════════════════════════════════════════════════════");sb.AppendLine($"Направление: {d.Direction}");sb.AppendLine($"Тип: {d.Type}");sb.AppendLine($"Номер: {d.Number}");sb.AppendLine($"Дата: {d.Date}");sb.AppendLine($"Статус: {d.Status}");sb.AppendLine($"Позиций: {d.Items}");sb.AppendLine($"ID: {d.Id}");sb.AppendLine();sb.AppendLine("ТОВАРЫ / БУТЫЛКИ");sb.AppendLine("────────────────────────────────────────────────────────────────");try{using var j=JsonDocument.Parse(d.RawJson);var root=j.RootElement;var arrays=new[]{"items","positions","products","productItems","product"};bool found=false;foreach(var key in arrays){if(!Find(root,key,out var arr)||arr.ValueKind!=JsonValueKind.Array)continue;int n=1;foreach(var item in arr.EnumerateArray()){found=true;var name=S(item,"name","productName","fullName","shortName","goodsName","alcoholName");var brand=S(item,"brand","brandName","tradeMark");var producer=S(item,"producer","producerName","manufacturer","manufacturerName","ownerName");var qty=S(item,"quantity","qty","amount","count");var volume=S(item,"volume","volumeValue","capacity","volumeMl","volumeL");var alc=S(item,"alcohol","alcoholVolume","alcoholPercent","strength");var price=S(item,"price","sum","cost");var mark=S(item,"mark","barcode","exciseMark","markCode","ean","barcodeDataMatrix");var code=S(item,"code","productCode","alcCode","catalogCode","fsrarId");sb.AppendLine($"{n}. {Fallback(name,"Товар без названия")}");if(brand!="")sb.AppendLine($"   Бренд: {brand}");if(producer!="")sb.AppendLine($"   Производитель: {producer}");if(volume!="")sb.AppendLine($"   Объём: {volume}");if(alc!="")sb.AppendLine($"   Крепость: {alc}");if(qty!="")sb.AppendLine($"   Количество: {qty}");if(price!="")sb.AppendLine($"   Цена/сумма: {price}");if(code!="")sb.AppendLine($"   Код товара ЕГАИС: {code}");if(mark!="")sb.AppendLine($"   Акцизная марка: {mark}");sb.AppendLine();n++;}}if(!found)sb.AppendLine("Отдельный список товаров не передан в ответе. Все доступные поля сохранены ниже.");foreach(var key in new[]{"supplier","shipper","consignee","sender","receiver","transport","delivery","invoice","waybill","certificate","reference","ttn","act"})if(Find(root,key,out var v)){sb.AppendLine();sb.AppendLine(HumanTitle(key));sb.AppendLine(Flatten(v,"  "));}}catch{sb.AppendLine("Не удалось разобрать ответ. Исходные данные доступны на отдельной вкладке.");}return sb.ToString();}
 static string Fields(string raw){try{using var j=JsonDocument.Parse(raw);var sb=new System.Text.StringBuilder();Dump(j.RootElement,sb,"");return sb.ToString();}catch{return raw;}}
 static void Dump(JsonElement e,System.Text.StringBuilder sb,string path){if(e.ValueKind==JsonValueKind.Object){foreach(var p in e.EnumerateObject())Dump(p.Value,sb,path==""?p.Name:path+"."+p.Name);}else if(e.ValueKind==JsonValueKind.Array){int i=0;foreach(var x in e.EnumerateArray())Dump(x,sb,$"{path}[{i++}]");if(i==0)sb.AppendLine($"{path} = []");}else sb.AppendLine($"{path} = {e}");}
 static string Flatten(JsonElement e,string pad){if(e.ValueKind==JsonValueKind.Object)return string.Join(Environment.NewLine,e.EnumerateObject().Select(x=>$"{pad}{x.Name}: {Flatten(x.Value,pad+"  ")}"));if(e.ValueKind==JsonValueKind.Array)return string.Join(Environment.NewLine,e.EnumerateArray().Select((x,i)=>$"{pad}[{i}] {Flatten(x,pad+"  ")}"));return e.ToString();}
 static string Pretty(string raw){try{using var j=JsonDocument.Parse(raw);return JsonSerializer.Serialize(j.RootElement,new JsonSerializerOptions{WriteIndented=true});}catch{return raw;}}
 static string S(JsonElement e,params string[] keys){foreach(var k in keys)if(Find(e,k,out var v))return v.ToString();return "";}static string Fallback(string s,string f)=>string.IsNullOrWhiteSpace(s)?f:s;
 static string HumanTitle(string s)=>s switch{"supplier"=>"ПОСТАВЩИК","shipper"=>"ОТПРАВИТЕЛЬ","consignee"=>"ПОЛУЧАТЕЛЬ","receiver"=>"ПОЛУЧАТЕЛЬ","sender"=>"ОТПРАВИТЕЛЬ","transport"=>"ТРАНСПОРТ","delivery"=>"ДОСТАВКА","invoice"=>"СЧЁТ","waybill"=>"НАКЛАДНАЯ","certificate"=>"СПРАВКА / СЕРТИФИКАТ","reference"=>"СПРАВКА","ttn"=>"ТТН","act"=>"АКТ",_=>s.ToUpperInvariant()};
 static bool Find(JsonElement e,string key,out JsonElement value){if(e.ValueKind==JsonValueKind.Object){foreach(var p in e.EnumerateObject()){if(string.Equals(p.Name,key,StringComparison.OrdinalIgnoreCase)){value=p.Value;return true;}if(Find(p.Value,key,out value))return true;}}else if(e.ValueKind==JsonValueKind.Array)foreach(var x in e.EnumerateArray())if(Find(x,key,out value))return true;value=default;return false;}
}
