namespace UTMMonitor;

public sealed class MainForm : Form
{
    readonly UtmStore store=new(); readonly UtmClient client=new(); readonly DataGridView grid=new(); readonly ToolStripStatusLabel status=new(); readonly System.Windows.Forms.Timer timer=new(){Interval=10000};
    public MainForm(){Text="UTM Monitor"; Width=1100; Height=700; StartPosition=FormStartPosition.CenterScreen; var bar=new ToolStrip(); var add=new ToolStripButton("Добавить");var edit=new ToolStripButton("Изменить");var del=new ToolStripButton("Удалить");var check=new ToolStripButton("Проверить");var sync=new ToolStripButton("Синхронизация");bar.Items.AddRange([add,edit,del,check,sync,status]); Controls.Add(bar); grid.Dock=DockStyle.Fill;grid.AutoGenerateColumns=true;grid.ReadOnly=true;grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;Controls.Add(grid);grid.BringToFront(); add.Click+=(_,_)=>Add();edit.Click+=(_,_)=>Edit();del.Click+=(_,_)=>Delete();check.Click+=async(_,_)=>await Check();sync.Click+=async(_,_)=>await Check();Load+=(_,_)=>RefreshGrid();timer.Tick+=async(_,_)=>await Check();timer.Start();}
    void RefreshGrid(){grid.DataSource=store.All().Select(u=>new{u.Id,u.Name,u.Host,Port=u.Port,Enabled=u.Enabled,Status="—",Version="—"}).ToList();}
    Utm? Selected()=>grid.CurrentRow?.Cells[0].Value is int id?store.All().FirstOrDefault(x=>x.Id==id):null;
    void Add(){using var f=new EditForm();if(f.ShowDialog(this)==DialogResult.OK){store.Add(f.NameValue,f.HostValue,f.PortValue);RefreshGrid();}}
    void Edit(){var u=Selected();if(u==null)return;using var f=new EditForm(u);if(f.ShowDialog(this)==DialogResult.OK){store.Update(u.Id,f.NameValue,f.HostValue,f.PortValue,f.EnabledValue);RefreshGrid();}}
    void Delete(){var u=Selected();if(u==null)return;if(MessageBox.Show($"Удалить «{u.Name}»?","UTM Monitor",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)==DialogResult.Yes){store.Delete(u.Id);RefreshGrid();}}
    async Task Check(){var list=store.All().Where(x=>x.Enabled).ToList();if(list.Count==0){status.Text="Нет активных УТМ";return;} status.Text="Проверка…"; var results=await Task.WhenAll(list.Select(async u=>(u,await client.StatusAsync(u)))); foreach(var x in results){foreach(DataGridViewRow r in grid.Rows)if((int)r.Cells[0].Value==x.u.Id){r.Cells[5].Value=x.Item2.Online?"ONLINE":"OFFLINE";r.Cells[6].Value=x.Item2.Version??"—";}}status.Text=$"Проверено: {results.Length} · {DateTime.Now:HH:mm:ss}";}
}

sealed class EditForm:Form{readonly TextBox n=new(),h=new();readonly NumericUpDown p=new(){Minimum=1,Maximum=65535,Value=8080};readonly CheckBox e=new(){Text="Включён",Checked=true};public string NameValue=>n.Text.Trim();public string HostValue=>h.Text.Trim();public int PortValue=>(int)p.Value;public bool EnabledValue=>e.Checked;public EditForm(Utm? u=null){Text=u==null?"Добавить УТМ":"Изменить УТМ";Width=420;Height=240;FormBorderStyle=FormBorderStyle.FixedDialog;StartPosition=FormStartPosition.CenterParent;var b=new Button{Text="Сохранить",DialogResult=DialogResult.OK,Dock=DockStyle.Bottom};n.Text=u?.Name??"УТМ";h.Text=u?.Host??"127.0.0.1";p.Value=u?.Port??8080;e.Checked=u?.Enabled??true;var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=4,Padding=new Padding(12)};t.Controls.Add(new Label{Text="Название",AutoSize=true},0,0);t.Controls.Add(n,1,0);t.Controls.Add(new Label{Text="IP / Host",AutoSize=true},0,1);t.Controls.Add(h,1,1);t.Controls.Add(new Label{Text="Порт",AutoSize=true},0,2);t.Controls.Add(p,1,2);t.Controls.Add(e,1,3);Controls.Add(t);Controls.Add(b);AcceptButton=b;}}
