using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

namespace UTMMonitor;

public sealed class MainForm:Form
{
 readonly UtmDatabase db=new(); readonly UtmClient api=new();
 readonly DataGridView utmGrid=Grid(),docGrid=Grid(),certGrid=Grid(),markGrid=Grid(),historyGrid=Grid(),eventGrid=Grid();
 readonly TextBox log=new(){Multiline=true,Dock=DockStyle.Fill,ScrollBars=ScrollBars.Both,ReadOnly=true};
 readonly Label state=new(){AutoSize=true,Text="Готово"}; readonly Timer timer=new(){Interval=600000}; readonly ComboBox utmPick=new(){DropDownStyle=ComboBoxStyle.DropDownList,Width=280};
 readonly TextBox docSearch=new(){Width=230};

 public MainForm(){Text="UTM Monitor — ЕГАИС v0.1";Width=1500;Height=900;MinimumSize=new(1150,700);StartPosition=FormStartPosition.CenterScreen;Font=new("Segoe UI",9F);
  var tabs=new TabControl{Dock=DockStyle.Fill}; tabs.TabPages.Add(BuildDashboard());tabs.TabPages.Add(BuildDocuments());tabs.TabPages.Add(BuildMarks());tabs.TabPages.Add(BuildCertificates());tabs.TabPages.Add(BuildHistory());tabs.TabPages.Add(BuildLog());Controls.Add(tabs);
  Load+=async(_,_)=>{RefreshUtms();await CheckAll();if(SelectedUtm()!=null){await Sync();await LoadCertificates();LoadHistory();LoadEvents();}}; FormClosed+=(_,_)=>{timer.Stop();api.Dispose();}; timer.Tick+=async(_,_)=>await CheckAll(); timer.Start();
 }
 static DataGridView Grid()=>new(){Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AutoGenerateColumns=true,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill};
 Button Btn(string text,Action a){var b=new Button{Text=text,AutoSize=true,Height=30};b.Click+=(_,_)=>{try{a();}catch(Exception e){Write(e.ToString());}};return b;}
 Button Btn(string text,Func<Task> a){var b=new Button{Text=text,AutoSize=true,Height=30};b.Click+=async(_,_)=>{try{await a();}catch(Exception e){Write(e.ToString());}};return b;}
 TabPage BuildDashboard(){var p=new TabPage("УТМ");var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,Padding=new(8),WrapContents=false};foreach(var b in new[]{Btn("Добавить",Add),Btn("Изменить",Edit),Btn("Удалить",Delete),Btn("Проверить",async()=>await CheckAll()),Btn("Синхронизация",async()=>await Sync()),Btn("Открыть папку данных",OpenDataFolder)})top.Controls.Add(b);top.Controls.Add(state);p.Controls.Add(utmGrid);p.Controls.Add(top);utmGrid.CellDoubleClick+=(_,_)=>Edit();return p;}
 TabPage BuildDocuments(){var p=new TabPage("Документы / ТТН");var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,Padding=new(8),WrapContents=false};top.Controls.Add(new Label{Text="УТМ:",AutoSize=true,Padding=new(0,7,0,0)});top.Controls.Add(utmPick);top.Controls.Add(Btn("Обновить",async()=>await LoadDocumentsFromUtm()));top.Controls.Add(new Label{Text="Поиск:",AutoSize=true,Padding=new(12,7,0,0)});top.Controls.Add(docSearch);top.Controls.Add(Btn("Экспорт CSV",ExportDocuments));top.Controls.Add(Btn("Открыть ТТН",OpenDocument));docSearch.TextChanged+=(_,_)=>ApplyDocumentFilter();docGrid.CellDoubleClick+=(_,_)=>OpenDocument();p.Controls.Add(docGrid);p.Controls.Add(top);return p;}
 TabPage BuildMarks(){var p=new TabPage("Марки / QueryBarcode");var split=new SplitContainer{Dock=DockStyle.Fill,Orientation=Orientation.Horizontal,SplitterDistance=270};var box=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=7,Padding=new(12)};box.ColumnStyles.Add(new(SizeType.Absolute,145));box.ColumnStyles.Add(new(SizeType.Percent,100));var raw=new TextBox{Dock=DockStyle.Fill,Multiline=true};var type=new TextBox();var rank=new TextBox();var number=new TextBox();var result=new TextBox{Multiline=true,ReadOnly=true,Dock=DockStyle.Fill,ScrollBars=ScrollBars.Both};box.Controls.Add(new Label{Text="DataMatrix / строка",AutoSize=true},0,0);box.Controls.Add(raw,1,0);box.Controls.Add(new Label{Text="Type",AutoSize=true},0,1);box.Controls.Add(type,1,1);box.Controls.Add(new Label{Text="Rank",AutoSize=true},0,2);box.Controls.Add(rank,1,2);box.Controls.Add(new Label{Text="Number",AutoSize=true},0,3);box.Controls.Add(number,1,3);var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill};buttons.Controls.Add(Btn("Разобрать",()=>{var m=ParseMark(raw.Text);type.Text=m?.Type??"";rank.Text=m?.Rank??"";number.Text=m?.Number??"";result.Text=m==null?"Не удалось распознать Type/Rank/Number":"Распознано: Type="+m.Type+" Rank="+m.Rank+" Number="+m.Number;}));buttons.Controls.Add(Btn("Отправить в УТМ",async()=>{var u=SelectedUtm();if(u==null){result.Text="Выберите УТМ";return;}var m=new MarkParts(type.Text.Trim(),rank.Text.Trim(),number.Text.Trim(),raw.Text);if(m.Type==""||m.Rank==""||m.Number==""){result.Text="Заполните Type, Rank и Number";return;}state.Text="QueryBarcode…";var q=await api.QueryBarcodeAsync(u,m);result.Text=q.Message+(q.Ticket==null?"":"\r\nID: "+q.Ticket)+"\r\n\r\nОТВЕТ ЗАПРОСА:\r\n"+q.Raw;if(q.Success&&q.Ticket!=null){var t=await api.PollTicketAsync(u,q.Ticket);result.AppendText("\r\n\r\nОТВЕТ УТМ:\r\n"+t.Raw);db.SaveMarkResult(u.Id,null,raw.Text,m,t.Success?"OK":"TIMEOUT",t.Raw);db.Event(u.Id,t.Success?"INFO":"ERROR","QueryBarcode "+q.Ticket,t.Raw);}state.Text="Готово";await LoadMarks();}));buttons.Controls.Add(Btn("Очистить",()=>{raw.Clear();type.Clear();rank.Clear();number.Clear();result.Clear();}));box.Controls.Add(buttons,1,4);box.Controls.Add(result,1,5);box.Controls.Add(new Label{Text="Ответ ищется в Ticket / ReplyBarcode / ReplyMark. Результат сохраняется в SQLite.",AutoSize=true},1,6);split.Panel1.Controls.Add(box);var mt=new FlowLayoutPanel{Dock=DockStyle.Top,Height=42,Padding=new(6)};mt.Controls.Add(Btn("Обновить историю марок",async()=>await LoadMarks()));mt.Controls.Add(Btn("Экспорт CSV",ExportMarks));split.Panel2.Controls.Add(markGrid);split.Panel2.Controls.Add(mt);p.Controls.Add(split);return p;}
 TabPage BuildCertificates(){var p=new TabPage("RSA / GOST / сертификаты");var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,Padding=new(8)};top.Controls.Add(Btn("Получить из УТМ",async()=>await LoadCertificates()));top.Controls.Add(Btn("Показать сохранённые",LoadSavedCertificates));p.Controls.Add(certGrid);p.Controls.Add(top);return p;}
 TabPage BuildHistory(){var p=new TabPage("История / события");var tabs=new TabControl{Dock=DockStyle.Fill};var hp=new TabPage("Статусы");var ep=new TabPage("События");var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=42,Padding=new(6)};top.Controls.Add(Btn("Обновить",async()=>{LoadHistory();LoadEvents();await Task.CompletedTask;}));top.Controls.Add(Btn("Экспорт событий",ExportEvents));hp.Controls.Add(historyGrid);hp.Controls.Add(top);ep.Controls.Add(eventGrid);tabs.TabPages.Add(hp);tabs.TabPages.Add(ep);p.Controls.Add(tabs);return p;}
 TabPage BuildLog(){var p=new TabPage("Журнал");p.Controls.Add(log);return p;}
 void RefreshUtms(){var list=db.All();utmGrid.DataSource=list.Select(u=>new{ID=u.Id,Название=u.Name,Host=u.Host,Порт=u.Port,Включён=u.Enabled,Статус="—",HTTP="—",Время="—",Версия="—",FSRAR="—"}).ToList();utmPick.DataSource=null;utmPick.DataSource=list.ToList();utmPick.DisplayMember="Name";utmPick.ValueMember="Id";}
 Utm? SelectedUtm(){if(utmGrid.CurrentRow?.Cells.Count>0&&utmGrid.CurrentRow.Cells[0].Value is int id)return db.All().FirstOrDefault(x=>x.Id==id);return utmPick.SelectedItem as Utm;}
 DocumentRow? SelectedDocument(){if(docGrid.CurrentRow==null)return null;var id=docGrid.CurrentRow.Cells[0].Value?.ToString();return db.Documents(SelectedUtm()?.Id).FirstOrDefault(x=>x.Id==id);}
 void OpenDocument(){var d=SelectedDocument();if(d==null){MessageBox.Show("Выберите ТТН или справку в списке.","UTM Monitor");return;}using var f=new DocumentDetailsForm(d);f.ShowDialog(this);}
 async Task CheckAll(){var list=db.All().Where(x=>x.Enabled).ToList();if(list.Count==0){state.Text="Нет активных УТМ";return;}state.Text="Проверка…";var r=await Task.WhenAll(list.Select(async u=>(u,s:await api.StatusAsync(u))));foreach(var x in r){db.SaveStatus(x.u.Id,x.s);foreach(DataGridViewRow row in utmGrid.Rows)if(Convert.ToInt32(row.Cells[0].Value)==x.u.Id){row.Cells[5].Value=x.s.Online?"ONLINE":"OFFLINE";row.Cells[6].Value=x.s.HttpCode==0?"—":x.s.HttpCode.ToString();row.Cells[7].Value=x.s.ResponseMs+" ms";row.Cells[8].Value=x.s.Version??"—";row.Cells[9].Value=x.s.OwnerId??"—";}db.Event(x.u.Id,x.s.Online?"INFO":"ERROR",x.s.Online?$"UTM ONLINE {x.s.Version}":$"UTM OFFLINE: {x.s.Error}");}state.Text=$"Проверено {r.Length} · {DateTime.Now:HH:mm:ss}";LoadHistory();LoadEvents();}
 async Task Sync(){var u=SelectedUtm();if(u==null){MessageBox.Show("Выберите УТМ");return;}state.Text="Синхронизация…";var q=await api.OutQueueAsync(u);var incoming=await api.DocumentsAsync(u,"/api/db/in/list","Входящие");var outgoing=await api.DocumentsAsync(u,"/api/db/out/list","Исходящие");db.SaveDocuments(u.Id,incoming);db.SaveDocuments(u.Id,outgoing);db.SaveDocuments(u.Id,q);await LoadDocuments();await LoadMarks();db.Event(u.Id,"INFO",$"Синхронизация: API IN={incoming.Count}, API OUT={outgoing.Count}, /opt/out={q.Count}");state.Text=$"Синхронизация: {incoming.Count+outgoing.Count+q.Count} документов";Write($"{DateTime.Now:yyyy-MM-dd HH:mm:ss} {u.Name}: IN={incoming.Count}, OUT={outgoing.Count}, /opt/out={q.Count}");}
 async Task LoadDocumentsFromUtm(){var u=SelectedUtm();if(u==null)return;state.Text="Читаю УТМ…";var q=await api.OutQueueAsync(u);db.SaveDocuments(u.Id,q);await LoadDocuments();await LoadMarks();state.Text=$"Загружено из /opt/out: {q.Count}";}
 async Task LoadDocuments(){var u=SelectedUtm();if(u==null)return;docGrid.DataSource=db.Documents(u.Id).Select(x=>new{ID=x.Id,Направление=x.Direction,Тип=x.Type,Номер=string.IsNullOrWhiteSpace(x.Number)?"—":x.Number,Дата=string.IsNullOrWhiteSpace(x.Date)?"—":x.Date,Статус=string.IsNullOrWhiteSpace(x.Status)?"—":x.Status,Позиций=x.Items,РазмерRaw=$"{x.RawJson.Length:N0} байт"}).ToList();ApplyDocumentFilter();await Task.CompletedTask;}
 void ApplyDocumentFilter(){if(docGrid.DataSource is not System.Collections.IEnumerable src)return;var q=docSearch.Text.Trim();if(string.IsNullOrEmpty(q))return;var rows=db.Documents(SelectedUtm()?.Id).Where(x=>(x.Number+x.Type+x.Status+x.Direction+x.Id).Contains(q,StringComparison.OrdinalIgnoreCase)).Select(x=>new{ID=x.Id,Направление=x.Direction,Тип=x.Type,Номер=string.IsNullOrWhiteSpace(x.Number)?"—":x.Number,Дата=string.IsNullOrWhiteSpace(x.Date)?"—":x.Date,Статус=string.IsNullOrWhiteSpace(x.Status)?"—":x.Status,Позиций=x.Items,РазмерRaw=$"{x.RawJson.Length:N0} байт"}).ToList();docGrid.DataSource=rows;}
 async Task LoadMarks(){var u=SelectedUtm();markGrid.DataSource=db.Marks(u?.Id).Select(x=>new{ID=x.Id,Документ=x.DocumentId,Type=x.Type,Rank=x.Rank,Number=x.Number,Статус=x.Status,Проверено=x.CheckedAt,Марка=x.Raw}).ToList();await Task.CompletedTask;}
 async Task LoadCertificates(){var u=SelectedUtm();if(u==null){MessageBox.Show("Выберите УТМ");return;}var a=await api.CertificatesAsync(u);db.SaveCertificates(u.Id,a);ShowCertificates(a);db.Event(u.Id,"INFO",$"Получено сертификатов: {a.Count}");}
 void LoadSavedCertificates(){var u=SelectedUtm();if(u!=null)ShowCertificates(db.Certificates(u.Id));}
 void ShowCertificates(IEnumerable<CertificateInfo> a){certGrid.DataSource=a.Select(x=>new{Тип=x.Name,Subject=x.Subject,Issuer=x.Issuer,Окончание=x.NotAfter,Действителен=x.Valid}).ToList();}
 void LoadHistory(){var u=SelectedUtm();historyGrid.DataSource=u==null?Array.Empty<object>():db.History(u.Id).Select(x=>new{Время=x.CheckedAt,Статус=x.Online?"ONLINE":"OFFLINE",HTTP=x.HttpCode,Ответ=$"{x.ResponseMs} ms",Версия=x.Version,Ошибка=x.Error}).ToList();}
 void LoadEvents(){var u=SelectedUtm();eventGrid.DataSource=db.Events(u?.Id).Select(x=>new{Время=x.CreatedAt,Уровень=x.Level,Сообщение=x.Message,Raw=x.Raw}).ToList();}
 void Add(){using var f=new EditForm();if(f.ShowDialog(this)==DialogResult.OK){if(string.IsNullOrWhiteSpace(f.N)||string.IsNullOrWhiteSpace(f.H)){MessageBox.Show("Название и Host обязательны.");return;}db.Add(f.N,f.H,f.P);RefreshUtms();}}
 void Edit(){var u=SelectedUtm();if(u==null)return;using var f=new EditForm(u);if(f.ShowDialog(this)==DialogResult.OK){db.Update(u,f.N,f.H,f.P,f.E);RefreshUtms();}}
 void Delete(){var u=SelectedUtm();if(u==null)return;if(MessageBox.Show($"Удалить «{u.Name}» и всю сохранённую историю?","UTM Monitor",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)==DialogResult.Yes){db.Delete(u.Id);RefreshUtms();}}
 void OpenDataFolder(){try{Process.Start(new ProcessStartInfo("explorer.exe",db.DataDirectory){UseShellExecute=true});}catch(Exception e){Write(e.ToString());}}
 void ExportDocuments(){var rows=db.Documents(SelectedUtm()?.Id);ExportCsv("documents.csv",new[]{"ID","Type","Direction","Number","Date","Status","Items"},rows.Select(x=>new[]{x.Id,x.Type,x.Direction,x.Number,x.Date,x.Status,x.Items.ToString()}));}
 void ExportMarks(){var rows=db.Marks(SelectedUtm()?.Id);ExportCsv("marks.csv",new[]{"ID","Document","Type","Rank","Number","Status","CheckedAt","Raw"},rows.Select(x=>new[]{x.Id.ToString(),x.DocumentId,x.Type,x.Rank,x.Number,x.Status,x.CheckedAt,x.Raw}));}
 void ExportEvents(){var rows=db.Events(SelectedUtm()?.Id);ExportCsv("events.csv",new[]{"CreatedAt","Level","Message","Raw"},rows.Select(x=>new[]{x.CreatedAt,x.Level,x.Message,x.Raw}));}
 void ExportCsv(string defaultName,string[] header,IEnumerable<string[]> rows){using var s=new SaveFileDialog{FileName=defaultName,Filter="CSV UTF-8|*.csv"};if(s.ShowDialog(this)!=DialogResult.OK)return;var sb=new StringBuilder();sb.AppendLine(string.Join(';',header.Select(Csv)));foreach(var r in rows)sb.AppendLine(string.Join(';',r.Select(Csv)));File.WriteAllText(s.FileName,sb.ToString(),new UTF8Encoding(true));MessageBox.Show("Экспорт завершён.","UTM Monitor");}
 static string Csv(string s)=>"\""+(s??"").Replace("\"","\"\"")+"\"";
 void Write(string s){if(IsDisposed)return;BeginInvoke(()=>log.AppendText(s+Environment.NewLine));}
 static MarkParts? ParseMark(string raw){if(string.IsNullOrWhiteSpace(raw))return null;var clean=raw.Replace("\u001d","");var m=Regex.Match(clean,@"(?<type>\d{3})[^0-9]{0,3}(?<rank>\d{3})[^0-9]{0,3}(?<num>\d{8})");if(m.Success)return new(m.Groups["type"].Value,m.Groups["rank"].Value,m.Groups["num"].Value,raw);var digits=new string(clean.Where(char.IsDigit).ToArray());return digits.Length>=14?new(digits[..3],digits.Substring(3,3),digits.Substring(6,8),raw):null;}
 protected override void OnFormClosing(FormClosingEventArgs e){api.Dispose();base.OnFormClosing(e);}
}

public sealed class EditForm:Form
{
 readonly TextBox n=new(),h=new();readonly NumericUpDown p=new(){Minimum=1,Maximum=65535,Value=8080};readonly CheckBox en=new(){Text="Включён",Checked=true};
 public string N=>n.Text.Trim();public string H=>h.Text.Trim();public int P=>(int)p.Value;public bool E=>en.Checked;
 public EditForm(Utm? u=null){Text=u==null?"Добавить УТМ":"Изменить УТМ";Width=430;Height=260;FormBorderStyle=FormBorderStyle.FixedDialog;StartPosition=FormStartPosition.CenterParent;var ok=new Button{Text="Сохранить",DialogResult=DialogResult.OK,Dock=DockStyle.Bottom,Height=38};var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=4,Padding=new(14)};t.ColumnStyles.Add(new(SizeType.Absolute,100));t.ColumnStyles.Add(new(SizeType.Percent,100));n.Text=u?.Name??"УТМ";h.Text=u?.Host??"127.0.0.1";p.Value=u?.Port??8080;en.Checked=u?.Enabled??true;t.Controls.Add(new Label{Text="Название",AutoSize=true},0,0);t.Controls.Add(n,1,0);t.Controls.Add(new Label{Text="IP / Host",AutoSize=true},0,1);t.Controls.Add(h,1,1);t.Controls.Add(new Label{Text="Порт",AutoSize=true},0,2);t.Controls.Add(p,1,2);t.Controls.Add(en,1,3);Controls.Add(t);Controls.Add(ok);AcceptButton=ok;}
}