using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;
namespace UTMMonitor;
public sealed class UtmClient : IDisposable
{
 private readonly HttpClient _http=new(new SocketsHttpHandler{ConnectTimeout=TimeSpan.FromSeconds(2),PooledConnectionLifetime=TimeSpan.FromMinutes(5)}){Timeout=TimeSpan.FromSeconds(8)};
 private static string Base(Utm u)=>$"http://{u.Host}:{u.Port}";
 public async Task<(int Code,string Text,long Ms)> GetAsync(Utm u,string path,CancellationToken ct=default){var sw=Stopwatch.StartNew();try{using var r=await _http.GetAsync(Base(u)+path,ct);return((int)r.StatusCode,await r.Content.ReadAsStringAsync(ct),sw.ElapsedMilliseconds);}catch(Exception e){return(0,e.Message,sw.ElapsedMilliseconds);}}
 public async Task<UtmStatus> StatusAsync(Utm u,CancellationToken ct=default){var x=await GetAsync(u,"/api/info/list",ct);if(x.Code==0)return new(false,0,x.Ms,null,null,null,null,x.Text,null,null);try{using var d=JsonDocument.Parse(x.Text);string? F(params string[] k){foreach(var z in k)if(TryFind(d.RootElement,z,out var v))return v.ToString();return null;}return new(x.Code<400,x.Code,x.Ms,F("version","utmVersion"),F("contour","contourName"),F("ownerId","fsrarId","clientId"),null,x.Code>=400?x.Text:null,null,null);}catch{return new(x.Code<400,x.Code,x.Ms,null,null,null,null,x.Code>=400?x.Text:null,null,null);}}
 static bool TryFind(JsonElement e,string key,out JsonElement value){if(e.ValueKind==JsonValueKind.Object){foreach(var p in e.EnumerateObject()){if(string.Equals(p.Name,key,StringComparison.OrdinalIgnoreCase)){value=p.Value;return true;}if(TryFind(p.Value,key,out value))return true;}}else if(e.ValueKind==JsonValueKind.Array){foreach(var i in e.EnumerateArray())if(TryFind(i,key,out value))return true;}value=default;return false;}
 public async Task<List<CertificateInfo>> CertificatesAsync(Utm u,CancellationToken ct=default){var a=new List<CertificateInfo>();foreach(var path in new[]{"/api/certificate/list","/api/certificate/GOST"}){var x=await GetAsync(u,path,ct);if(x.Code<200||x.Code>=400)continue;try{using var d=JsonDocument.Parse(x.Text);IEnumerable<JsonElement> A(JsonElement e){if(e.ValueKind==JsonValueKind.Array)return e.EnumerateArray();foreach(var k in new[]{"certificates","data","result"})if(e.ValueKind==JsonValueKind.Object&&e.TryGetProperty(k,out var z))return A(z);return []; }foreach(var v in A(d.RootElement)){string F(string k)=>TryFind(v,k,out var z)?z.ToString():"";var n=F("name");a.Add(new(n.Length>0?n:path.Contains("GOST",StringComparison.OrdinalIgnoreCase)?"GOST":"RSA",F("subject"),F("issuer"),F("expireDate").Length>0?F("expireDate"):F("notAfter"),true,v.GetRawText()));}}catch{}}return a;}
 public async Task<List<DocumentRow>> DocumentsAsync(Utm u,string path,string direction,CancellationToken ct=default){var x=await GetAsync(u,path,ct);if(x.Code<200||x.Code>=400)return [];try{using var d=JsonDocument.Parse(x.Text);var a=new List<DocumentRow>();IEnumerable<JsonElement> A(JsonElement e){if(e.ValueKind==JsonValueKind.Array)return e.EnumerateArray();foreach(var k in new[]{"documents","items","data","result"})if(e.ValueKind==JsonValueKind.Object&&e.TryGetProperty(k,out var z))return A(z);return [];}foreach(var v in A(d.RootElement)){string F(params string[] k){foreach(var z in k)if(TryFind(v,z,out var q))return q.ToString();return "";}var id=F("id","uuid","documentId","identity");if(id=="")id=Guid.NewGuid().ToString();a.Add(new(id,F("type","documentType","docType"),direction,F("number","docNumber"),F("date","dateTime","created"),F("status","state"),0,v.GetRawText()));}return a;}catch{return [];}}
 public async Task<SyncResult> SyncAsync(Utm u,CancellationToken ct=default){var i=await DocumentsAsync(u,"/api/db/in/list","Входящие",ct);var o=await DocumentsAsync(u,"/api/db/out/list","Исходящие",ct);return new(i.Count,o.Count,i.Count+o.Count,"Синхронизация завершена");}
 public async Task<QueryResult> QueryBarcodeAsync(Utm u,MarkParts p,CancellationToken ct=default){var esc=System.Security.SecurityElement.Escape;var xml=$"<?xml version=\"1.0\" encoding=\"UTF-8\"?><ns:QueryBarcode xmlns:ns=\"http://fsrar.ru/WEGAIS/QueryBarcode\"><ns:Query><ns:Type>{esc(p.Type)}</ns:Type><ns:Rank>{esc(p.Rank)}</ns:Rank><ns:Number>{esc(p.Number)}</ns:Number></ns:Query></ns:QueryBarcode>";using var form=new MultipartFormDataContent();form.Add(new StringContent(xml,Encoding.UTF8,"application/xml"),"xml_file","QueryBarcode.xml");try{using var r=await _http.PostAsync(Base(u)+"/opt/in/QueryBarcode",form,ct);var t=await r.Content.ReadAsStringAsync(ct);return r.IsSuccessStatusCode?new(true,"Запрос отправлен",FindTicket(t),t):new(false,$"UTM HTTP {(int)r.StatusCode}",null,t);}catch(Exception e){return new(false,e.Message,null,"");}}
 static string? FindTicket(string s){try{return XDocument.Parse(s).Descendants().FirstOrDefault(e=>e.Name.LocalName.Contains("Ticket",StringComparison.OrdinalIgnoreCase))?.Value;}catch{return null;}}
 public void Dispose()=>_http.Dispose();
}