using Microsoft.Data.Sqlite;

namespace UTMMonitor;

public sealed class UtmDatabase
{
    private readonly string _cs;
    public UtmDatabase()
    {
        var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"UTMMonitor"); Directory.CreateDirectory(dir);
        _cs=$"Data Source={Path.Combine(dir,"utm-monitor.sqlite")};Cache=Shared";
        using var c=Open();
        foreach(var sql in new[]{
            "PRAGMA journal_mode=WAL;","PRAGMA busy_timeout=5000;",
            "CREATE TABLE IF NOT EXISTS utms(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,host TEXT NOT NULL,port INTEGER NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);",
            "CREATE TABLE IF NOT EXISTS documents(id INTEGER PRIMARY KEY AUTOINCREMENT,utm_id INTEGER NOT NULL,external_id TEXT NOT NULL,type TEXT,direction TEXT,number TEXT,date TEXT,status TEXT,items INTEGER NOT NULL DEFAULT 0,raw TEXT,updated_at TEXT NOT NULL,UNIQUE(utm_id,external_id));",
            "CREATE INDEX IF NOT EXISTS ix_documents_utm_date ON documents(utm_id,date);",
            "CREATE TABLE IF NOT EXISTS document_items(id INTEGER PRIMARY KEY AUTOINCREMENT,utm_id INTEGER NOT NULL,document_external_id TEXT NOT NULL,item_key TEXT NOT NULL,name TEXT,quantity REAL,price REAL,mark TEXT,raw TEXT,updated_at TEXT NOT NULL,UNIQUE(utm_id,document_external_id,item_key));",
            "CREATE TABLE IF NOT EXISTS marks(id INTEGER PRIMARY KEY AUTOINCREMENT,utm_id INTEGER NOT NULL,document_external_id TEXT,raw TEXT,type TEXT,rank TEXT,number TEXT,status TEXT,response TEXT,checked_at TEXT,UNIQUE(utm_id,document_external_id,raw));",
            "CREATE TABLE IF NOT EXISTS status_history(id INTEGER PRIMARY KEY AUTOINCREMENT,utm_id INTEGER NOT NULL,checked_at TEXT NOT NULL,online INTEGER NOT NULL,http_code INTEGER NOT NULL,response_ms INTEGER NOT NULL,version TEXT,error TEXT);",
            "CREATE TABLE IF NOT EXISTS certificates(id INTEGER PRIMARY KEY AUTOINCREMENT,utm_id INTEGER NOT NULL,name TEXT,subject TEXT,issuer TEXT,not_after TEXT,valid INTEGER NOT NULL,raw TEXT,updated_at TEXT NOT NULL,UNIQUE(utm_id,name,subject));",
            "CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,utm_id INTEGER,created_at TEXT NOT NULL,level TEXT NOT NULL,message TEXT NOT NULL,raw TEXT);"
        }) using(var q=c.CreateCommand()){q.CommandText=sql;q.ExecuteNonQuery();}
        using var count=c.CreateCommand(); count.CommandText="SELECT COUNT(*) FROM utms";
        if(Convert.ToInt64(count.ExecuteScalar())==0){using var i=c.CreateCommand();i.CommandText="INSERT INTO utms(name,host,port,enabled) VALUES('УТМ 1','127.0.0.1',8080,1)";i.ExecuteNonQuery();}
    }
    private SqliteConnection Open(){var c=new SqliteConnection(_cs);c.Open();return c;}
    public List<Utm> All(){using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT id,name,host,port,enabled FROM utms ORDER BY id";using var r=q.ExecuteReader();var a=new List<Utm>();while(r.Read())a.Add(new((int)r.GetInt64(0),r.GetString(1),r.GetString(2),(int)r.GetInt64(3),r.GetInt64(4)!=0));return a;}
    public int Add(string n,string h,int p){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO utms(name,host,port,enabled) VALUES($n,$h,$p,1);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$n",n);q.Parameters.AddWithValue("$h",h);q.Parameters.AddWithValue("$p",p);return Convert.ToInt32(q.ExecuteScalar());}
    public void Update(Utm u,string n,string h,int p,bool e){using var c=Open();using var q=c.CreateCommand();q.CommandText="UPDATE utms SET name=$n,host=$h,port=$p,enabled=$e WHERE id=$id";q.Parameters.AddWithValue("$n",n);q.Parameters.AddWithValue("$h",h);q.Parameters.AddWithValue("$p",p);q.Parameters.AddWithValue("$e",e?1:0);q.Parameters.AddWithValue("$id",u.Id);q.ExecuteNonQuery();}
    public void Delete(int id){using var c=Open();using var q=c.CreateCommand();q.CommandText="DELETE FROM utms WHERE id=$id";q.Parameters.AddWithValue("$id",id);q.ExecuteNonQuery();}
    public void SaveDocuments(int uid,IEnumerable<DocumentRow> rows){using var c=Open();using var tx=c.BeginTransaction();foreach(var d in rows){using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO documents(utm_id,external_id,type,direction,number,date,status,items,raw,updated_at) VALUES($u,$x,$t,$d,$n,$dt,$s,$i,$r,$now) ON CONFLICT(utm_id,external_id) DO UPDATE SET type=$t,direction=$d,number=$n,date=$dt,status=$s,items=$i,raw=$r,updated_at=$now";q.Parameters.AddWithValue("$u",uid);q.Parameters.AddWithValue("$x",d.Id);q.Parameters.AddWithValue("$t",d.Type);q.Parameters.AddWithValue("$d",d.Direction);q.Parameters.AddWithValue("$n",d.Number);q.Parameters.AddWithValue("$dt",d.Date);q.Parameters.AddWithValue("$s",d.Status);q.Parameters.AddWithValue("$i",d.Items);q.Parameters.AddWithValue("$r",d.RawJson);q.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();}tx.Commit();}
    public List<DocumentRow> Documents(int? uid=null){using var c=Open();using var q=c.CreateCommand();q.CommandText=uid.HasValue?"SELECT external_id,type,direction,number,date,status,items,raw FROM documents WHERE utm_id=$u ORDER BY date DESC":"SELECT external_id,type,direction,number,date,status,items,raw FROM documents ORDER BY date DESC";if(uid.HasValue)q.Parameters.AddWithValue("$u",uid.Value);using var r=q.ExecuteReader();var a=new List<DocumentRow>();while(r.Read())a.Add(new(r.GetString(0),r.IsDBNull(1)?"":r.GetString(1),r.IsDBNull(2)?"":r.GetString(2),r.IsDBNull(3)?"":r.GetString(3),r.IsDBNull(4)?"":r.GetString(4),r.IsDBNull(5)?"":r.GetString(5),r.GetInt32(6),r.IsDBNull(7)?"":r.GetString(7)));return a;}
    public void SaveStatus(int uid,UtmStatus s){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO status_history(utm_id,checked_at,online,http_code,response_ms,version,error) VALUES($u,$t,$o,$h,$m,$v,$e)";q.Parameters.AddWithValue("$u",uid);q.Parameters.AddWithValue("$t",DateTime.UtcNow.ToString("O"));q.Parameters.AddWithValue("$o",s.Online?1:0);q.Parameters.AddWithValue("$h",s.HttpCode);q.Parameters.AddWithValue("$m",s.ResponseMs);q.Parameters.AddWithValue("$v",s.Version??"");q.Parameters.AddWithValue("$e",s.Error??"");q.ExecuteNonQuery();}
    public void SaveCertificates(int uid,IEnumerable<CertificateInfo> list){using var c=Open();foreach(var x in list){using var q=c.CreateCommand();q.CommandText="INSERT INTO certificates(utm_id,name,subject,issuer,not_after,valid,raw,updated_at) VALUES($u,$n,$s,$i,$d,$v,$r,$t) ON CONFLICT(utm_id,name,subject) DO UPDATE SET issuer=$i,not_after=$d,valid=$v,raw=$r,updated_at=$t";q.Parameters.AddWithValue("$u",uid);q.Parameters.AddWithValue("$n",x.Name);q.Parameters.AddWithValue("$s",x.Subject??"");q.Parameters.AddWithValue("$i",x.Issuer??"");q.Parameters.AddWithValue("$d",x.NotAfter??"");q.Parameters.AddWithValue("$v",x.Valid?1:0);q.Parameters.AddWithValue("$r",x.RawJson);q.Parameters.AddWithValue("$t",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();}}
    public void Event(int? uid,string level,string message,string raw=""){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO events(utm_id,created_at,level,message,raw) VALUES($u,$t,$l,$m,$r)";q.Parameters.AddWithValue("$u",(object?)uid??DBNull.Value);q.Parameters.AddWithValue("$t",DateTime.UtcNow.ToString("O"));q.Parameters.AddWithValue("$l",level);q.Parameters.AddWithValue("$m",message);q.Parameters.AddWithValue("$r",raw);q.ExecuteNonQuery();}
}