using Microsoft.Data.Sqlite;
namespace UTMMonitor;
public sealed class UtmDatabase
{
 private readonly string _cs;
 public UtmDatabase(){var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"UTMMonitor");Directory.CreateDirectory(dir);_cs=$"Data Source={Path.Combine(dir,"utm-monitor.sqlite")};Cache=Shared";using var c=Open();foreach(var sql in new[]{"PRAGMA journal_mode=WAL;","PRAGMA busy_timeout=5000;","CREATE TABLE IF NOT EXISTS utms(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,host TEXT NOT NULL,port INTEGER NOT NULL,enabled INTEGER NOT NULL DEFAULT 1);","CREATE TABLE IF NOT EXISTS documents(id INTEGER PRIMARY KEY AUTOINCREMENT,utm_id INTEGER NOT NULL,external_id TEXT NOT NULL,type TEXT,direction TEXT,number TEXT,date TEXT,status TEXT,items INTEGER NOT NULL DEFAULT 0,raw TEXT,updated_at TEXT NOT NULL,UNIQUE(utm_id,external_id));","CREATE INDEX IF NOT EXISTS ix_documents_utm_date ON documents(utm_id,date);"})using(var x=c.CreateCommand()){x.CommandText=sql;x.ExecuteNonQuery();}using var q=c.CreateCommand();q.CommandText="SELECT COUNT(*) FROM utms";if(Convert.ToInt64(q.ExecuteScalar())==0){using var i=c.CreateCommand();i.CommandText="INSERT INTO utms(name,host,port,enabled) VALUES('УТМ 1','127.0.0.1',8080,1)";i.ExecuteNonQuery();}}
 SqliteConnection Open(){var c=new SqliteConnection(_cs);c.Open();return c;}
 public List<Utm> All(){using var c=Open();using var q=c.CreateCommand();q.CommandText="SELECT id,name,host,port,enabled FROM utms ORDER BY id";using var r=q.ExecuteReader();var a=new List<Utm>();while(r.Read())a.Add(new((int)r.GetInt64(0),r.GetString(1),r.GetString(2),(int)r.GetInt64(3),r.GetInt64(4)!=0));return a;}
 public int Add(string name,string host,int port){using var c=Open();using var q=c.CreateCommand();q.CommandText="INSERT INTO utms(name,host,port,enabled) VALUES($n,$h,$p,1);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$n",name);q.Parameters.AddWithValue("$h",host);q.Parameters.AddWithValue("$p",port);return Convert.ToInt32(q.ExecuteScalar());}
 public void Update(Utm u,string name,string host,int port,bool enabled){using var c=Open();using var q=c.CreateCommand();q.CommandText="UPDATE utms SET name=$n,host=$h,port=$p,enabled=$e WHERE id=$id";q.Parameters.AddWithValue("$n",name);q.Parameters.AddWithValue("$h",host);q.Parameters.AddWithValue("$p",port);q.Parameters.AddWithValue("$e",enabled?1:0);q.Parameters.AddWithValue("$id",u.Id);q.ExecuteNonQuery();}
 public void Delete(int id){using var c=Open();using var q=c.CreateCommand();q.CommandText="DELETE FROM utms WHERE id=$id";q.Parameters.AddWithValue("$id",id);q.ExecuteNonQuery();}
 public void SaveDocuments(int utmId,IEnumerable<DocumentRow> rows){using var c=Open();using var tx=c.BeginTransaction();foreach(var d in rows){using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO documents(utm_id,external_id,type,direction,number,date,status,items,raw,updated_at) VALUES($u,$x,$t,$d,$n,$dt,$s,$i,$r,$now) ON CONFLICT(utm_id,external_id) DO UPDATE SET type=$t,direction=$d,number=$n,date=$dt,status=$s,items=$i,raw=$r,updated_at=$now";q.Parameters.AddWithValue("$u",utmId);q.Parameters.AddWithValue("$x",d.Id);q.Parameters.AddWithValue("$t",d.Type);q.Parameters.AddWithValue("$d",d.Direction);q.Parameters.AddWithValue("$n",d.Number);q.Parameters.AddWithValue("$dt",d.Date);q.Parameters.AddWithValue("$s",d.Status);q.Parameters.AddWithValue("$i",d.Items);q.Parameters.AddWithValue("$r",d.RawJson);q.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));q.ExecuteNonQuery();}tx.Commit();}
 public List<DocumentRow> Documents(int? utmId=null){using var c=Open();using var q=c.CreateCommand();q.CommandText=utmId.HasValue?"SELECT external_id,type,direction,number,date,status,items,raw FROM documents WHERE utm_id=$u ORDER BY date DESC":"SELECT external_id,type,direction,number,date,status,items,raw FROM documents ORDER BY date DESC";if(utmId.HasValue)q.Parameters.AddWithValue("$u",utmId.Value);using var r=q.ExecuteReader();var a=new List<DocumentRow>();while(r.Read())a.Add(new(r.GetString(0),r.IsDBNull(1)?"":r.GetString(1),r.IsDBNull(2)?"":r.GetString(2),r.IsDBNull(3)?"":r.GetString(3),r.IsDBNull(4)?"":r.GetString(4),r.IsDBNull(5)?"":r.GetString(5),r.GetInt32(6),r.IsDBNull(7)?"":r.GetString(7)));return a;}
}